name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Build Flutter
      run: flutter build aot
    #- name: Run tests
    #  run: flutter pub run test
    - name: Dart/Flutter Package Analyzer
      run: flutter analyze
    # name: SonarCloud Scan
    #  uses: SonarSource/sonarcloud-github-action@v1.1
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
