name: Dart CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        channel: 'stable'
    - name: Install dependencies
      run: flutter pub get
    - name: Build Flutter
      run: flutter build aot
    #- name: Run tests
    #  run: flutter pub run test
    - name: Dart/Flutter Package Analyzer
      uses: axel-op/dart-package-analyzer@v2.0.0
      with:
        # Token to connect to Github. Use secrets.GITHUB_TOKEN
        githubToken: secrets.GITHUB_TOKEN
        # Path of your package in your repository
        relativePath: flutter_app 
        # Minimum level for annotations. Accepted values are [info, warning, error].
        minAnnotationLevel: warning
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@v1.1
